// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Weather.Web.DbContext;

#nullable disable

namespace Weather.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240225054612_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("Weather.Web.Entity.WeatherRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AirPressure")
                        .HasColumnType("REAL");

                    b.Property<byte?>("Cloudiness")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<double>("Humidity")
                        .HasColumnType("REAL");

                    b.Property<int?>("LowCloudiness")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Td")
                        .HasColumnType("REAL");

                    b.Property<double>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<double?>("VV")
                        .HasColumnType("REAL");

                    b.Property<string>("WeatherEvent")
                        .HasColumnType("TEXT");

                    b.Property<string>("WindDirection")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WindSpeed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
